### ISSUE TITLE
[TASK] Setup development database

### ISSUE THREAD

**Issue by IsaacClank** [IsaacClank/vigor#14]
# Description

## Todo

- [x] Dockerfile for development Postgres database.
- [x] Update composer file for user module.
- [x] Setup outbox replication slot in db to support Transactional Outbox pattern.
- [x] Support custom initialization.
